import type { WorkloadDetail, WorkloadSummaryResponse } from "@/lib/api";

/** Same strings as `EXCLUDED_CODES` in api.ts — inlined to avoid circular import (api → demo-store → this file → api). */
const XC = {
  GPU_WORKLOAD: "GPU_WORKLOAD",
  MEMORY_HPA: "MEMORY_HPA",
  CPU_HPA: "CPU_HPA",
} as const;

const cons = (
  o: Partial<WorkloadDetail["constraints"]> = {}
): WorkloadDetail["constraints"] => ({
  blockingConsolidation: false,
  pdb: false,
  doNotDisruptAnnotation: false,
  volume: false,
  affinity: false,
  topologySpreadConstraint: false,
  podAntiAffinity: false,
  excludedAnnotation: false,
  isGPUWorkload: false,
  ...o,
});

const cfg = (
  o: Partial<WorkloadDetail["config"]> & Pick<WorkloadDetail["config"], "criticalityLevel" | "cruiseEnabled">
): WorkloadDetail["config"] => ({
  disruptionSchedule: [],
  inDisruptionWindow: false,
  hpaEnabled: false,
  ...o,
});

const resCpu = (
  current: number,
  rec: { min: number; avg: number; max: number; change: number },
  podAvg: number
): WorkloadDetail["cpu"] => ({
  current,
  pod_current_avg: podAvg,
  recommended: { ...rec },
});

const resMem = (
  current: number,
  rec: { min: number; avg: number; max: number; change: number },
  podAvg: number
): WorkloadDetail["memory"] => ({
  current,
  pod_current_avg: podAvg,
  recommended: { ...rec },
});

/** Reliability $ only when recommended increases CPU or memory (positive `change`). */
function applyReliabilityExpenditureRule(w: WorkloadDetail): WorkloadDetail {
  const cpuUp = w.cpu.recommended.change > 1e-9;
  const memUp = w.memory.recommended.change > 1e-9;
  return {
    ...w,
    dollarExpenditurePerMonth: cpuUp || memUp ? w.dollarExpenditurePerMonth : 0,
  };
}

/** Rows from production `GET .../workloads/summary` (cluster `default`). */
const WORKLOADS_FROM_API: WorkloadDetail[] = [
  {
    workloadID: "Deployment:pranjal-ws:tfy-llm-gateway-test-ask-user-qs",
    kind: "Deployment",
    namespace: "pranjal-ws",
    name: "tfy-llm-gateway-test-ask-user-qs",
    updatedAt: 1778647095,
    podsCount: 1,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(1, { min: 0.177, avg: 0.177, max: 0.177, change: -0.823 }, 1),
    memory: resMem(512, { min: 441, avg: 441, max: 441, change: -71 }, 512),
    dollarSavingsPerMonth: 8.96274,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:truefoundry:tfy-llm-gateway-test-approval",
    kind: "Deployment",
    namespace: "truefoundry",
    name: "tfy-llm-gateway-test-approval",
    updatedAt: 1778646890,
    podsCount: 1,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(1, { min: 0.192, avg: 0.192, max: 0.192, change: -0.808 }, 1),
    memory: resMem(512, { min: 1024, avg: 1024, max: 1024, change: 512 }, 512),
    dollarSavingsPerMonth: 8.43552,
    dollarExpenditurePerMonth: 2.6726400000000003,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:truefoundry:tfy-flyte-scheduler",
    kind: "Deployment",
    namespace: "truefoundry",
    name: "tfy-flyte-scheduler",
    updatedAt: 1778646666,
    podsCount: 1,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(0.1, { min: 0.002, avg: 0.002, max: 0.002, change: -0.098 }, 0.1),
    memory: resMem(128, { min: 35, avg: 35, max: 35, change: -93 }, 128),
    dollarSavingsPerMonth: 1.50858,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
];

/** Extra synthetic rows so filters, icons, and modals can exercise every constraint / exclusion path. */
const WORKLOADS_EXTRA_CASES: WorkloadDetail[] = [
  {
    workloadID: "Deployment:demo-cases:gpu-inference",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "gpu-inference",
    updatedAt: 1778646000,
    podsCount: 2,
    scaledDown: false,
    constraints: cons({ isGPUWorkload: true }),
    cpu: resCpu(8, { min: 8, avg: 8, max: 8, change: 0 }, 7.2),
    memory: resMem(16384, { min: 16384, avg: 16384, max: 16384, change: 0 }, 14000),
    dollarSavingsPerMonth: 0,
    dollarExpenditurePerMonth: 95,
    config: cfg({
      criticalityLevel: "medium",
      cruiseEnabled: false,
      excludedCodes: [XC.GPU_WORKLOAD],
    }),
  },
  {
    workloadID: "Deployment:demo-cases:hpa-cpu-only",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "hpa-cpu-only",
    updatedAt: 1778645900,
    podsCount: 3,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(2, { min: 1.5, avg: 1.6, max: 1.7, change: -0.4 }, 0.9),
    memory: resMem(2048, { min: 1800, avg: 1900, max: 2000, change: -148 }, 1200),
    dollarSavingsPerMonth: 12,
    dollarExpenditurePerMonth: 0,
    config: cfg({
      criticalityLevel: "high",
      cruiseEnabled: false,
      hpaEnabled: true,
      excludedCodes: [XC.CPU_HPA],
    }),
  },
  {
    workloadID: "Deployment:demo-cases:hpa-memory-only",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "hpa-memory-only",
    updatedAt: 1778645800,
    podsCount: 2,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(1.5, { min: 1.2, avg: 1.3, max: 1.4, change: -0.2 }, 0.8),
    memory: resMem(4096, { min: 4096, avg: 4096, max: 4096, change: 0 }, 3500),
    dollarSavingsPerMonth: 4,
    dollarExpenditurePerMonth: 0,
    config: cfg({
      criticalityLevel: "medium",
      cruiseEnabled: false,
      hpaEnabled: true,
      excludedCodes: [XC.MEMORY_HPA],
    }),
  },
  {
    workloadID: "Deployment:demo-cases:hpa-both",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "hpa-both",
    updatedAt: 1778645700,
    podsCount: 4,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(4, { min: 3.5, avg: 3.7, max: 3.9, change: -0.3 }, 2.1),
    memory: resMem(8192, { min: 8192, avg: 8192, max: 8192, change: 0 }, 6000),
    dollarSavingsPerMonth: 0,
    dollarExpenditurePerMonth: 0,
    config: cfg({
      criticalityLevel: "low",
      cruiseEnabled: false,
      hpaEnabled: true,
      excludedCodes: [XC.CPU_HPA, XC.MEMORY_HPA],
    }),
  },
  {
    workloadID: "Deployment:demo-cases:pdb-dnd-mitigated",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "pdb-dnd-mitigated",
    updatedAt: 1778645600,
    podsCount: 5,
    scaledDown: false,
    constraints: cons({
      blockingConsolidation: true,
      pdb: true,
      doNotDisruptAnnotation: true,
    }),
    cpu: resCpu(3, { min: 2.2, avg: 2.4, max: 2.6, change: -0.6 }, 1.8),
    memory: resMem(4096, { min: 3072, avg: 3200, max: 3400, change: -896 }, 2800),
    dollarSavingsPerMonth: 42,
    dollarExpenditurePerMonth: 6,
    config: cfg({
      criticalityLevel: "high",
      cruiseEnabled: true,
      inDisruptionWindow: true,
      disruptionSchedule: [
        { windowStartCron: "0 22 * * 1", windowEndCron: "0 4 * * 2" },
        { windowStartCron: "0 12 * * 5", windowEndCron: "0 18 * * 5" },
      ],
    }),
  },
  {
    workloadID: "Deployment:demo-cases:blocking-only",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "blocking-only",
    updatedAt: 1778645500,
    podsCount: 2,
    scaledDown: false,
    constraints: cons({ blockingConsolidation: true }),
    cpu: resCpu(1, { min: 0.8, avg: 0.85, max: 0.9, change: -0.15 }, 0.55),
    memory: resMem(1024, { min: 800, avg: 850, max: 900, change: -174 }, 700),
    dollarSavingsPerMonth: 18,
    dollarExpenditurePerMonth: 0,
    config: cfg({
      criticalityLevel: "medium",
      cruiseEnabled: true,
      inDisruptionWindow: false,
      disruptionSchedule: [],
    }),
  },
  {
    workloadID: "StatefulSet:demo-cases:volume-blocked",
    kind: "StatefulSet",
    namespace: "demo-cases",
    name: "volume-blocked",
    updatedAt: 1778645400,
    podsCount: 1,
    scaledDown: false,
    constraints: cons({ volume: true, blockingConsolidation: true }),
    cpu: resCpu(0.5, { min: 0.45, avg: 0.48, max: 0.5, change: -0.02 }, 0.4),
    memory: resMem(512, { min: 480, avg: 500, max: 512, change: -12 }, 400),
    dollarSavingsPerMonth: 3,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:demo-cases:topology-spread",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "topology-spread",
    updatedAt: 1778645300,
    podsCount: 6,
    scaledDown: false,
    constraints: cons({ topologySpreadConstraint: true }),
    cpu: resCpu(6, { min: 5.5, avg: 5.7, max: 5.9, change: -0.3 }, 4.2),
    memory: resMem(12288, { min: 11000, avg: 11500, max: 12000, change: -788 }, 9000),
    dollarSavingsPerMonth: 55,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "high", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:demo-cases:pod-anti-affinity",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "pod-anti-affinity",
    updatedAt: 1778645200,
    podsCount: 3,
    scaledDown: false,
    constraints: cons({ podAntiAffinity: true }),
    cpu: resCpu(3, { min: 2.8, avg: 2.9, max: 3, change: -0.1 }, 2.4),
    memory: resMem(6144, { min: 5800, avg: 6000, max: 6100, change: -144 }, 5200),
    dollarSavingsPerMonth: 22,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:demo-cases:excluded-annotation",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "excluded-annotation",
    updatedAt: 1778645100,
    podsCount: 1,
    scaledDown: false,
    constraints: cons({ excludedAnnotation: true }),
    cpu: resCpu(2, { min: 2, avg: 2, max: 2, change: 0 }, 1.2),
    memory: resMem(4096, { min: 4096, avg: 4096, max: 4096, change: 0 }, 3000),
    dollarSavingsPerMonth: 0,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "very-high", cruiseEnabled: false }),
  },
  {
    workloadID: "Job:demo-cases:batch-etl",
    kind: "Job",
    namespace: "demo-cases",
    name: "batch-etl",
    updatedAt: 1778645000,
    podsCount: 1,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(4, { min: 1.2, avg: 1.5, max: 2, change: -2.5 }, 0.9),
    memory: resMem(8192, { min: 2048, avg: 3072, max: 4096, change: -5120 }, 1800),
    dollarSavingsPerMonth: 120,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "low", cruiseEnabled: true }),
  },
  {
    workloadID: "DaemonSet:demo-cases:log-collector",
    kind: "DaemonSet",
    namespace: "demo-cases",
    name: "log-collector",
    updatedAt: 1778644900,
    podsCount: 12,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(1.2, { min: 0.4, avg: 0.5, max: 0.6, change: -0.7 }, 0.35),
    memory: resMem(512, { min: 256, avg: 288, max: 320, change: -224 }, 200),
    dollarSavingsPerMonth: 28,
    dollarExpenditurePerMonth: 1.2,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:demo-cases:checkout-api",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "checkout-api",
    updatedAt: 1778644850,
    podsCount: 4,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(2, { min: 0.9, avg: 1, max: 1.1, change: -1 }, 0.65),
    memory: resMem(4096, { min: 2048, avg: 2560, max: 3072, change: -1536 }, 1500),
    dollarSavingsPerMonth: 76,
    dollarExpenditurePerMonth: 0,
    config: cfg({
      criticalityLevel: "high",
      cruiseEnabled: true,
      disruptionSchedule: [{ windowStartCron: "0 1 * * 6", windowEndCron: "0 6 * * 6" }],
      inDisruptionWindow: false,
    }),
  },
  {
    workloadID: "Deployment:production:orders-worker",
    kind: "Deployment",
    namespace: "production",
    name: "orders-worker",
    updatedAt: 1778644820,
    podsCount: 6,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(3, { min: 1.1, avg: 1.25, max: 1.4, change: -1.75 }, 0.95),
    memory: resMem(6144, { min: 4096, avg: 4608, max: 5120, change: -1536 }, 2800),
    dollarSavingsPerMonth: 64,
    dollarExpenditurePerMonth: 3.5,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:staging:catalog-api",
    kind: "Deployment",
    namespace: "staging",
    name: "catalog-api",
    updatedAt: 1778644780,
    podsCount: 3,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(1.5, { min: 0.55, avg: 0.62, max: 0.7, change: -0.88 }, 0.48),
    memory: resMem(3072, { min: 1536, avg: 1792, max: 2048, change: -1280 }, 1100),
    dollarSavingsPerMonth: 52,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:production:payments-bff",
    kind: "Deployment",
    namespace: "production",
    name: "payments-bff",
    updatedAt: 1778644760,
    podsCount: 5,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(4, { min: 1.8, avg: 2, max: 2.2, change: -2 }, 1.4),
    memory: resMem(8192, { min: 5120, avg: 5632, max: 6144, change: -2560 }, 4200),
    dollarSavingsPerMonth: 142,
    dollarExpenditurePerMonth: 8,
    config: cfg({
      criticalityLevel: "high",
      cruiseEnabled: true,
      disruptionSchedule: [{ windowStartCron: "0 23 * * 0", windowEndCron: "0 5 * * 1" }],
      inDisruptionWindow: false,
    }),
  },
  {
    workloadID: "Deployment:demo-cases:search-indexer",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "search-indexer",
    updatedAt: 1778644740,
    podsCount: 2,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(2, { min: 0.75, avg: 0.85, max: 0.95, change: -1.15 }, 0.55),
    memory: resMem(16384, { min: 12288, avg: 13312, max: 14336, change: -3072 }, 9000),
    dollarSavingsPerMonth: 98,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "low", cruiseEnabled: true }),
  },
  {
    workloadID: "Deployment:monitoring:alert-router",
    kind: "Deployment",
    namespace: "monitoring",
    name: "alert-router",
    updatedAt: 1778644735,
    podsCount: 2,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(0.5, { min: 0.22, avg: 0.25, max: 0.28, change: -0.25 }, 0.18),
    memory: resMem(1024, { min: 640, avg: 704, max: 768, change: -320 }, 520),
    dollarSavingsPerMonth: 34,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:production:inventory-sync",
    kind: "Deployment",
    namespace: "production",
    name: "inventory-sync",
    updatedAt: 1778644720,
    podsCount: 4,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(2.5, { min: 1.4, avg: 1.55, max: 1.7, change: -0.95 }, 1.1),
    memory: resMem(4096, { min: 3072, avg: 3328, max: 3584, change: -768 }, 2400),
    dollarSavingsPerMonth: 41,
    dollarExpenditurePerMonth: 1.8,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: true }),
  },
  {
    workloadID: "StatefulSet:staging:kafka-broker-lite",
    kind: "StatefulSet",
    namespace: "staging",
    name: "kafka-broker-lite",
    updatedAt: 1778644700,
    podsCount: 3,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(6, { min: 4.5, avg: 5, max: 5.5, change: -1 }, 3.8),
    memory: resMem(24576, { min: 20000, avg: 21504, max: 23040, change: -3072 }, 18000),
    dollarSavingsPerMonth: 185,
    dollarExpenditurePerMonth: 12,
    config: cfg({
      criticalityLevel: "very-high",
      cruiseEnabled: true,
      disruptionSchedule: [
        { windowStartCron: "0 10 * * 3", windowEndCron: "0 14 * * 3" },
      ],
      inDisruptionWindow: false,
    }),
  },
  {
    workloadID: "Deployment:demo-cases:very-high-cruise",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "very-high-cruise",
    updatedAt: 1778644800,
    podsCount: 8,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(16, { min: 14, avg: 15, max: 15.5, change: -1 }, 12),
    memory: resMem(65536, { min: 60000, avg: 62000, max: 64000, change: -3536 }, 48000),
    dollarSavingsPerMonth: 210,
    dollarExpenditurePerMonth: 15,
    config: cfg({
      criticalityLevel: "very-high",
      cruiseEnabled: true,
      disruptionSchedule: [{ windowStartCron: "0 2 * * *", windowEndCron: "0 5 * * *" }],
      inDisruptionWindow: false,
    }),
  },
  {
    workloadID: "Deployment:staging:otel-receiver",
    kind: "Deployment",
    namespace: "staging",
    name: "otel-receiver",
    updatedAt: 1778644660,
    podsCount: 2,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(0.8, { min: 0.35, avg: 0.4, max: 0.45, change: -0.4 }, 0.3),
    memory: resMem(1536, { min: 768, avg: 896, max: 1024, change: -640 }, 600),
    dollarSavingsPerMonth: 19,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:demo-cases:rec-only-sidecar",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "rec-only-sidecar",
    updatedAt: 1778644650,
    podsCount: 3,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(1.2, { min: 0.5, avg: 0.55, max: 0.6, change: -0.65 }, 0.42),
    memory: resMem(2048, { min: 1024, avg: 1152, max: 1280, change: -896 }, 800),
    dollarSavingsPerMonth: 27,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "high", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:production:cart-cache",
    kind: "Deployment",
    namespace: "production",
    name: "cart-cache",
    updatedAt: 1778644640,
    podsCount: 4,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(2.5, { min: 1.6, avg: 1.75, max: 1.9, change: -0.75 }, 1.3),
    memory: resMem(4096, { min: 3072, avg: 3328, max: 3584, change: -768 }, 2600),
    dollarSavingsPerMonth: 36,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "low", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:monitoring:grafana-agent",
    kind: "Deployment",
    namespace: "monitoring",
    name: "grafana-agent",
    updatedAt: 1778644630,
    podsCount: 2,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(0.25, { min: 0.08, avg: 0.1, max: 0.12, change: -0.15 }, 0.07),
    memory: resMem(768, { min: 384, avg: 448, max: 512, change: -320 }, 300),
    dollarSavingsPerMonth: 11,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:demo-cases:cpu-up-recommend-only",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "cpu-up-recommend-only",
    updatedAt: 1778644620,
    podsCount: 2,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(0.4, { min: 0.55, avg: 0.6, max: 0.65, change: 0.2 }, 0.32),
    memory: resMem(512, { min: 400, avg: 450, max: 480, change: -62 }, 380),
    dollarSavingsPerMonth: 6,
    dollarExpenditurePerMonth: 5.4,
    config: cfg({ criticalityLevel: "medium", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:staging:mem-up-recommend-only",
    kind: "Deployment",
    namespace: "staging",
    name: "mem-up-recommend-only",
    updatedAt: 1778644610,
    podsCount: 3,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(2, { min: 1.8, avg: 1.85, max: 1.9, change: -0.15 }, 1.6),
    memory: resMem(2048, { min: 2560, avg: 2816, max: 3072, change: 768 }, 1900),
    dollarSavingsPerMonth: 4,
    dollarExpenditurePerMonth: 11.5,
    config: cfg({ criticalityLevel: "high", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:kube-public:cluster-info-rbac",
    kind: "Deployment",
    namespace: "kube-public",
    name: "cluster-info-rbac",
    updatedAt: 1778644600,
    podsCount: 1,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(0.05, { min: 0.05, avg: 0.05, max: 0.05, change: 0 }, 0.04),
    memory: resMem(128, { min: 128, avg: 128, max: 128, change: 0 }, 100),
    dollarSavingsPerMonth: 0,
    dollarExpenditurePerMonth: 0,
    config: cfg({ criticalityLevel: "low", cruiseEnabled: false }),
  },
  {
    workloadID: "Deployment:demo-cases:both-up-recommend-only",
    kind: "Deployment",
    namespace: "demo-cases",
    name: "both-up-recommend-only",
    updatedAt: 1778644590,
    podsCount: 2,
    scaledDown: false,
    constraints: cons(),
    cpu: resCpu(1, { min: 1.25, avg: 1.35, max: 1.45, change: 0.35 }, 0.88),
    memory: resMem(1024, { min: 1536, avg: 1792, max: 2048, change: 768 }, 900),
    dollarSavingsPerMonth: 0,
    dollarExpenditurePerMonth: 18.25,
    config: cfg({ criticalityLevel: "very-high", cruiseEnabled: false }),
  },
];

const IMPACT_FROM_API: WorkloadSummaryResponse["impactSummary"] = {
  dollarCurrentCost: 4915.40256,
  dollarCurrentSavings: 6652.177537510075,
  dollarPossibleSavings: 4762.958294254613,
  clusterResources: {
    cpu: {
      utilised: 10.735,
      requested: 124.604,
      allocatable: 184.66,
    },
    memory: {
      utilised: 235.134,
      requested: 351.758,
      allocatable: 572.328,
    },
  },
};

export function createDemoWorkloadSummary(): WorkloadSummaryResponse {
  const workloadDetails = [...WORKLOADS_FROM_API, ...WORKLOADS_EXTRA_CASES].map(
    applyReliabilityExpenditureRule
  );
  return {
    impactSummary: { ...IMPACT_FROM_API },
    workloadDetails,
  };
}
